-- MySQL Script generated by MySQL Workbench
-- Sun Jan 28 10:24:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
USE order_management;

CREATE TABLE IF NOT EXISTS customers (
  `customer_id` INT NOT NULL,
  `customer_name` VARCHAR(30) NULL,
  `address` VARCHAR(150) NULL,
  `email` VARCHAR(30) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;
DROP TABLE customers;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  `order_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `order_date` DATE NULL,
  `total_amount` DECIMAL NULL, 
  PRIMARY KEY (`order_id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES customers (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;
DROP TABLE orders;



-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(30) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;
DROP TABLE categories;



-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(30) NULL,
  `category_id` INT NULL,
  `price` DECIMAL NULL,
  PRIMARY KEY (`product_id`),
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES categories (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
DROP TABLE products;


-- -----------------------------------------------------
-- Table `mydb`.`orderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS orderDetails (
  `order_detail_id` INT NOT NULL,
  `order_id` INT NULL,
  `product_id` INT NULL,
  `quantity` INT NULL,
  `unit_price` DECIMAL NULL,
  `status` BIT NULL DEFAULT 1,
  PRIMARY KEY (`order_detail_id`),
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES orders (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES products (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
DROP TABLE orderdetails;


-- -----------------------------------------------------
-- Table `mydb`.`shipping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS shipping (
  `customer_id` INT NOT NULL,
  `order_id` INT NULL,
  `shipping_date` DATE NULL,
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  
    FOREIGN KEY (`customer_id`)
    REFERENCES customers (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`order_id`)
    REFERENCES orders (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
DROP TABLE shipping;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
